# Generated by Django 4.0.1 on 2022-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_producer',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log in to volunteer via this site.', verbose_name='producer'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_requester',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log in to make requests on this site.', verbose_name='requester'),
        ),
    ]
